services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_bot_token
      - key: MONGO_URI
        value: your_mongodb_uri
      - key: OWNER_ID
        value: "2085275594 1623892821"
